version: "3"
services:
  postgres:
    image: postgres
    restart: always
    ports:
     - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}

  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=true
    ports:
      - ${REDIS_PORT}:6379
