version: "3"
services:
  posgres:
    image: postgres
    restart: always
    ports:
     - 5432:5432
    environment:
      POSTGRES_PASSWORD: auction
      POSTGRES_USER: root
      POSTGRES_DB: auction
