swagger: '2.0'

info:
  version: '1.0.0'
  title: 'Auction'
  license:
    name: ''

schemes:
  - 'http'

paths:
  /signup:
    post:
      summary: 'SignUp'
      operationId: 'signup'
      parameters:
        - in: body
          name: body
          description: 'User object'
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: 'Return user entity'
          schema:
            type: object
            properties:
              data:
                $ref: '#/definitions/User'
        400:
          description: 'Validation error'
          schema:
            $ref: '#/definitions/ValidationError'

  /signin:
    post:
      summary: 'sign up'
      operationId: signUp
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/SignIn'
      responses:
        200:
          description: 'Successfully signed in'
          schema:
            type: object
            properties:
              data:
                $ref: '#/definitions/SignInData'
        400:
          description: 'Validation error'
          schema:
            $ref: '#/definitions/ValidationError'
        401:
          description: 'Email not confirmed'
          schema:
            $ref: '#/definitions/AppError'

  /confirmation/{uuidToken}:
    post:
      summary: 'Confirmation profile'
      operationId: confirmation
      parameters:
        - in: path
          name: uuidToken
          schema:
            type: string
          required: true
      responses:
        200:
          description: 'Profile confirmed'
          schema:
            type: object
            properties:
              data:
                $ref: '#/definitions/User'
        404:
          description: 'Model not found'
          schema:
            $ref: '#/definitions/AppError'

        403:
          description: 'Token revoked'
          schema:
            $ref: '#/definitions/AppError'

  /password/recovery:
    post:
      summary: 'Password recovery'
      operationId: passwordRecovery
      parameters:
        - in: body
          name: body
          description: 'User email'
          required: true
          schema:
            $ref: '#/definitions/PasswordRecovery'
      responses:
        200:
          description: 'Check email with password recovery link'
          schema:
            type: object
            properties:
              data:
                type: string
                example: null
        400:
          description: 'Validation error'
          schema:
            $ref: '#/definitions/ValidationError'

        401:
          description: 'Unauthorized. Email not confirmed'
          schema:
            $ref: '#/definitions/AppError'

  /password/update/{uuidToken}:
    post:
      summary: 'Password update'
      operationId: passwordUpdate
      parameters:
        - in: path
          name: uuidToken
          required: true
          schema:
            type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/PasswordUpdate'
      responses:
        200:
          description: 'Password updated'
          schema:
            type: object
            properties:
              data:
                $ref: '#/definitions/User'
        404:
          description: 'Token not found'
          schema:
            $ref: '#/definitions/AppError'
        400:
          description: 'Validation error'
          schema:
            $ref: '#/definitions/ValidationError'

  /marketplace/lots:
    get:
      security:
        - JWTToken: []
      summary: 'List lots onli in process status'
      operationId: allLots
      responses:
        200:
          description: 'List Lots'
          schema:
            type: object
            properties:
              data:
                $ref: '#/definitions/LotList'
    post:
      security:
        - JWTToken: []
      summary: 'Create lot'
      operationId: createLot
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Lot'
      responses:
        200:
          description: 'Successfully created lot'
          schema:
            type: object
            properties:
              data:
                $ref: '#/definitions/Lot'
        400:
          description: 'Validation error'
          schema:
            $ref: '#/definitions/ValidationError'
        422:
          description: 'End time must be more start time'
          schema:
            $ref: '#/definitions/AppError'

  /marketplace/lots/my:
    get:
      security:
        - JWTToken: []
      summary: 'Lots list with filtering'
      operationId: myLots
      parameters:
        - in: query
          name: type
          required: false
          schema:
            type: string
            enum:
              - all
              - created
              - participation
          default: 'all'
        - in: query
          name: page
          required: true
          schema:
            type: integer
          default: 1
      responses:
        200:
          description: 'List Lots'
          schema:
            type: object
            properties:
              data:
                $ref: '#/definitions/LotList'

  /marketplace/lots/{id}:
    get:
      security:
        - JWTToken: []
      summary: 'Return lot'
      operationId: showLot
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: 'Lot'
          schema:
            type: object
            properties:
              data:
                $ref: '#/definitions/Lot'
        404:
          description: 'Model not found'
          schema:
            $ref: '#/definitions/AppError'
    delete:
      security:
        - JWTToken: []
      summary: 'Remove lot when PENDING STATUS'
      operationId: deleteLot
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: 'Null response'
        403:
          description: 'Delete only in PENDING status'
          schema:
            $ref: '#/definitions/AppError'
        404:
          description: 'Model not found'
          schema:
            $ref: '#/definitions/AppError'

securityDefinitions:
  JWTToken:
    type: apiKey
    in: header
    name: Authorization
    description: 'Example: Authorization Bearer bf24725aa32d1febc3477b61dc32220aBHbny43RsEjVTTR35t2bcOkrJtACkjI4HkATEOHNDMgdQfwouIi0OTDlXV6myY8K'

definitions:

  LotList:
    type: array
    items:
      $ref: '#/definitions/Lot'

  Lot:
    type: object
    properties:
      title:
        type: string
        example: 'Phone'
      image:
        type: string
        example: '/images/example_image.jpg'
        description: |
          When we create lot, fill image as base64 without metadata with type
          Example: https://pastebin.com/WSwumqD2
      description:
        type: string
      current_price:
        type: number
        example: 12.33
      estimated_price:
        type: number
        example: 120.00
      status:
        type: string
        enum: [0, 1, 2]
        description: >
          `0` - PENDING
          `1` - PROCESS
          `2` - CLOSED
        example: 0
        default: 0
        readOnly: true
      start_time:
        type: string
        example: '2004-10-19 10:23:54+02'
      end_time:
        type: string
        example: '2004-10-19 10:23:54+02'
      user_id:
        type: integer
        readOnly: true
      created_at:
        type: string
        readOnly: true
      updated_at:
        type: string
        readOnly: true
    required:
      - title
      - current_price
      - estimated_price
      - start_time
      - end_time

  AppError:
    type: object
    properties:
      errors:
        type: string
      message:
        type: string

  SignIn:
    type: object
    properties:
      email:
        type: string
        example: 'example1@g.com'
      password:
        type: string
        example: '12345678'

  PasswordRecovery:
    type: object
    properties:
      email:
        type: string
        example: 'example1@g.com'

  SignInData:
    type: object
    properties:
      user:
        $ref: '#/definitions/User'
      personal:
        $ref: '#/definitions/JWTToken'

  JWTToken:
    type: object
    properties:
      token:
        type: string
        example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjQxLCJpYXQiOjE1NDQyNzU2MzZ9.AMzvxvjpI7dYcqMWXFu2wHwyGUfAVnbrQAZLd0OoEa4'
      type:
        type: string
        example: 'bearer'
      refreshToken:
        type: string
        example: null

  PasswordUpdate:
    type: object
    properties:
      password:
        type: string
        example: '12345678'
      password_confirmation:
        type: string
        example: '12345678'

  ValidationItem:
    type: object
    properties:
      field:
        type: string
      message:
        type: string
      validation:
        type: string

  ValidationError:
    type: object
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/ValidationItem'
      message:
        type: string

  User:
    type: object
    properties:
      id:
        type: integer
        required: false
        readOnly: true
      email:
        type: string
        example: 'example1@g.com'
      phone:
        type: string
        example: '234234237423'
      password:
        type: string
        example: '12345678'
      first_name:
        type: string
        example: 'FirstName'
      lastname:
        type: string
        example: 'LastName'
      birth_day:
        format: date
        pattern: '\d{4}-\d{1,2}-\d{1,2}'
        type: string
        example: '1996-11-10'
      created_at:
        type: string
        readOnly: true
      updated_at:
        type: string
        readOnly: true
    required:
      - email
      - password
      - phone
      - first_name
      - lastname
      - birthday
